### PR TITLE
Adding csv files for different microarchitectures

### PR DESCRIPTION
**Pull request by andreas-abel**

### CODE REVIEW

**Comment by travisdowns** [comment]
@andreas-abel - thanks, this is awesome! I'll try to update the SO post with the graphs from this dump.

Sorry on the delay responding to this PR as I was traveling.

**Comment by travisdowns** [comment]
@andreas-abel  - one question: do you know if the loop buffer (LSD) was enabled on the Skylake/Kaby/Coffee lake machines you tested on? Intel disabled the loop buffer with a microcode update to fix [a bug](http://gallium.inria.fr/blog/intel-skylake-bug/) in Skylake, but depending on what OS you choose and if you've installed the microcode package or not, it may or may not be disabled.

I think on Coffee lake it is disabled already in the out-of-the-box microcode by Intel, but Kabylake I'm not sure.

It's important here because much of the behavior for small loops depends heavily on the LSD.

If you don't know, no worries, it will probably be obvious from the graphs...

**Comment by andreas-abel** [comment]
The commit does not contain results for Skylake and Kaby Lake; however, I could also run the tests on these machines if you are interested in them.

The Coffee Lake machine is a i7-8700K with Ubuntu 16.04.5 and microcode version 0x96.

**Comment by travisdowns** [comment]
@andreas-abel - sorry I did not look carefully enough at the files, and for some reason thought there were Skylake and/or Kaby Lake in there.

No, I don't think we need those results: Kaby Lake should be identical to Skylake, and I already tested Skylake since that's what I have. I tested it back before I updated my microcode, so I get the LSD "effect" which is probably the main interesting effect for this study, but by now I've updated so i don't see it anymore (so in fact the chip is more efficient in this test than it used to be, at least in terms of raw performance, although perhaps not performance/watt or something like that). It is still possible to roll back the microcode to get the LSD working again, but it is annoying...

**Comment by travisdowns** [comment]
@andreas-abel any chance you could include Haswell results? I have some, but I want to double check them since I'm seeing a variance between the Broadwell results you provided and Haswell which I had provided by another person, and yet I'd expect to BDL and HSW be the same.

**Comment by andreas-abel** [comment]
I can also include Haswell, however, the machine is currently being used by someone else, so it will take a couple of days until I can run the tests.

**Pull request merged**
